#!/usr/bin/env ruby
require './app'
require './helpers'

def main
  puts "Welcome to School Library App!\n\n"
  app = App.new
  helpers = Helpers.new
  response = nil
  helpers.selection(app, response)
end

main
